name: Scan Securite PetClinic

on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Scan Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: 'pom.xml' # C'est LA modification qui sauve la mémoire du serveur
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          timeout: '15m'
          scanners: 'vuln'